version: "3.8"

networks:
  server:

configs:
  mongo:
    file: ./db/mongo-init.js

services:
  server:
    container_name: nexomia-server
    build: .
    restart: always
    depends_on:
      - config
      - mongo
      - minio
    networks:
      - server

  config:
    container_name: nexomia-config
    image: kobionic/node-config-server
    restart: always
    networks:
      - server
    ports:
      - 20490:20490
    volumes:
      - ./config:/app/config:ro

  mongo:
    container_name: nexomia-mongo
    image: mongo
    restart: always
    networks:
      - server
    configs:
      - source: mongo
        target: /docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nexomia
      MONGO_INITDB_DATABASE: NexomiaNew

  mongo-express:
    container_name: nexomia-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - server
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://nexomiaDev:deNewOxima1202@mongo:27017/NexomiaNew

  minio:
    container_name: nexomia-minio
    image: minio/minio
    restart: always
    networks:
      - server
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: minio server /data --console-address ":9001"